### ISSUE TITLE
[enhancement] Display usage, support `--summary` option

### ISSUE THREAD

**Issue by m-ueberall** [olastor/clevis-pin-fido2#1]
As of `clevis` release version 19, the upstream encryption/decryption scripts associated with pins will display a one-line explanation when called from `clevis` with the `--summary` option, and a more detailed explanation when called individually (in the absence of `stdin` redirection).
The attached patch [usage_summary_patch.txt](https://github.com/olastor/clevis-pin-fido2/files/14921554/usage_summary_patch.txt) adds the above functionality.

**Comment by olastor** [comment]
@m-ueberall Thank you for the suggestion. I've added the summary!
